services:
  db:
    build:
      context: ./backend/db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-climbing_db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5240}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5240}:5432"

  redis:
    image: redis:alpine
    restart: always

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5240}/${POSTGRES_DB:-climbing_db}
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - POSTGRES_PORT=${POSTGRES_PORT:-5240}
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://${SERVER_IP:-localhost}:8000 # Default for local/single-server browser access
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=http://${SERVER_IP:-localhost}:3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_API_URL=http://${SERVER_IP:-localhost}:8000
    depends_on:
      - backend

volumes:
  postgres_data:
